name: Compatibility test

on:
  workflow_dispatch:

jobs:
  minimum-dependencies:
    runs-on: ubuntu-latest

    strategy:
      fail-test: false
      matrix:
        python:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        - "3.14"

    name: python ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v7
      
      - uses: astral-sh/setup-uv@v10.0.1
      
      - name: Install Python
        run: uv python install ${{ matrix.python }}

      - name: Install minimum dependencies
        run: |
          uv sync --python ${{ matrix.python }}

      - name Show versions
        run: |
          uv run --no-sync python --version
          uv run python -c "import numpy; print(numpy.__version__)"
          uv run python -c "import pandas; print(pandas.__version__)"
          uv run python -c "import fastparquet; print(fastparquet.__version__)"

      - name: Run test CSV
        run: |
          uv run --no-sync python3 GenerateCSV.py --yes

#      - name: Run test Plot
#        run: uv run --no-sync python3 GeneratePlot.py --yes