name: Compatibility test

on:
  workflow_dispatch:

jobs:
  minimum-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      
      - uses: astral-sh/setup-uv@v10.0.1
      
      - name: Install Python
        run: uv python install 3.8

      - name: Install minimum dependencies
        run: uv sync --python 3.8 --resolution lowest-direct

      - name: Run test CSV
        run: uv run --no-sync python3 GenerateCSV.py

      - name: Run test Plot
        run: uv run --no-sync python3 GeneratePlot.py